-- Valor padr�o de conteudo

USE [VENDAS SUCOS]

CREATE TABLE TAB_PADRAO
(
	ID INT IDENTITY (1,1) NOT NULL,
	DESCRITOR VARCHAR(20) NULL,
	ENDERECO VARCHAR(200) NULL,
	CIDADE VARCHAR(50) DEFAULT 'Cidade n�o definida',
	DATA_CRIACAO DATE DEFAULT GETDATE()
)

INSERT INTO TAB_PADRAO (DESCRITOR, ENDERECO, CIDADE, DATA_CRIACAO) 
VALUES ('CLIENTE X', 'RUA PROJETADA A', 'S�O PAULO', '2018-04-30')

SELECT * FROM TAB_PADRAO

INSERT INTO TAB_PADRAO (DESCRITOR) VALUES ('CLIENTE X')

SELECT * FROM TAB_PADRAO