-- Número de notas salvas em uma tabela

/*
Continue evoluindo o script da resposta do exercício anterior. Agora, inclua o dia e o número de notas em uma tabela.

Segue o script do exercício anterior:

	DECLARE @DATAINICIAL DATE
	DECLARE @DATAFINAL DATE
	DECLARE @NUMNOTAS INT
	SET @DATAINICIAL = '20170101'
	SET @DATAFINAL = '20170110'
	WHILE @DATAINICIAL <= @DATAFINAL
	BEGIN
		SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS] 
			WHERE DATA = @DATAINICIAL
		PRINT CONVERT(VARCHAR(10), @DATAINICIAL) + ' --> ' 
			+ CONVERT(VARCHAR(10), @NUMNOTAS)
		SELECT @DATAINICIAL = DATEADD(DAY, 1, @DATAINICIAL)
	END
*/


USE [SUCOS_VENDAS]

-- Se a tabela [TABELANOTAS] existir no banco, ela será excluida
IF OBJECT_ID('TABELANOTAS','U') IS NOT NULL
	DROP TABLE TABELANOTAS

-- Criação da tabela auxiliar
CREATE TABLE TABELANOTAS (DATA DATE, NUMNOTAS INT)

--Declaração de variáveis
DECLARE @DATAINICIAL DATE
DECLARE @DATAFINAL DATE
DECLARE @NUMNOTAS INT

SET @DATAINICIAL = '20170101'
SET @DATAFINAL = '20170110'

-- Percorre cada Nota Fiscal e preenche a quantidade de notas por data
WHILE @DATAINICIAL <= @DATAFINAL
BEGIN
    SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS] 
        WHERE DATA = @DATAINICIAL
    INSERT INTO TABELANOTAS (DATA, NUMNOTAS) 
        VALUES (@DATAINICIAL, @NUMNOTAS)
    SELECT @DATAINICIAL = DATEADD(DAY, 1, @DATAINICIAL)
END
SELECT * FROM TABELANOTAS