-- SPs com parâmetros de saída

USE [SUCOS_VENDAS]

SELECT COUNT(*) FROM [NOTAS FISCAIS] AS [QUANTIDADE NFS] WHERE CPF = '19290992743'
AND YEAR([DATA]) = 2016

SELECT SUM(QUANTIDADE * [PREÇO]) AS [VALOR FATURAMENTO] FROM [ITENS NOTAS FISCAIS] B
INNER JOIN [NOTAS FISCAIS] A ON A.NUMERO = B.NUMERO
WHERE CPF = '19290992743'
AND YEAR([DATA]) = 2016

CREATE PROCEDURE RetornaValores
@CPF AS VARCHAR(12),
@ANO AS INT,
@NUM_NOTAS AS INT OUTPUT,
@FATURAMENTO AS FLOAT OUTPUT
AS
BEGIN
   SELECT @NUM_NOTAS = COUNT(*) 
   FROM [NOTAS FISCAIS] 
   WHERE 1 = 1 
   AND CPF = @CPF
   AND YEAR([DATA]) = @ANO

   SELECT @FATURAMENTO = SUM(QUANTIDADE * [PREÇO]) 
   FROM [ITENS NOTAS FISCAIS] B
   INNER JOIN [NOTAS FISCAIS] A 
   ON A.NUMERO = B.NUMERO
   WHERE 1 = 1 
   AND CPF = @CPF
   AND YEAR([DATA]) = @ANO
END 

DECLARE @NUMERO_NOTAS INT, @FATURAMENTO FLOAT
DECLARE @CPF VARCHAR(12), @ANO INT
SET @CPF = '19290992743'
SET @ANO = 2016
EXEC RetornaValores @CPF = @CPF, @ANO = @ANO
, @NUM_NOTAS = @NUMERO_NOTAS OUTPUT, @FATURAMENTO = @FATURAMENTO OUTPUT
SELECT @NUMERO_NOTAS AS [QUANTIDADE NFS], @FATURAMENTO AS [VALOR FATURAMENTO]










