-- Tratando erro na inclusão de um vendedor com TRY-CATCH

USE [SUCOS_VENDAS]

-- Crie uma nova SP chamada InclusaoVendedor02, agora tratando o erro com TRY-CATCH. Crie a SP:

CREATE PROCEDURE InclusaoVendedor02
@MATRICULA AS VARCHAR(5), @NOME AS VARCHAR(100), 
    @PERCENTUAL AS FLOAT,
@DATAADMISSAO AS DATE, @FERIAS AS BIT, @BAIRRO AS VARCHAR(50), 
@MENSAGEM VARCHAR(100) OUTPUT
AS
BEGIN
    BEGIN TRY
        INSERT INTO [TABELA DE VENDEDORES] (MATRICULA, NOME, 
            [PERCENTUAL COMISSÃO], [DATA ADMISSÃO], [DE FERIAS], BAIRRO)
        VALUES (@MATRICULA, @NOME, @PERCENTUAL, @DATAADMISSAO, @FERIAS, @BAIRRO)
    END TRY
BEGIN CATCH
    SET @MENSAGEM = 'Houve um erro número: ' + CONVERT(VARCHAR(10), @@ERROR)
END CATCH
END

-- E depois execute-a:
CREATE PROCEDURE InclusaoVendedor02
@MATRICULA AS VARCHAR(5), @NOME AS VARCHAR(100), 
    @PERCENTUAL AS FLOAT,
@DATAADMISSAO AS DATE, @FERIAS AS BIT, @BAIRRO AS VARCHAR(50), 
@MENSAGEM VARCHAR(100) OUTPUT
AS
BEGIN
    BEGIN TRY
        INSERT INTO [TABELA DE VENDEDORES] (MATRICULA, NOME, 
            [PERCENTUAL COMISSÃO], [DATA ADMISSÃO], [DE FERIAS], BAIRRO)
        VALUES (@MATRICULA, @NOME, @PERCENTUAL, @DATAADMISSAO, @FERIAS, @BAIRRO)
    END TRY
BEGIN CATCH
    SET @MENSAGEM = 'Houve um erro número: ' + CONVERT(VARCHAR(10), @@ERROR)
END CATCH
END