-- Select com controle de fluxo

USE [SUCOS_VENDAS]

SELECT * FROM [TABELA DE CLIENTES]

SELECT SUM([LIMITE DE CREDITO]) AS [LIMITE DE CREDITO]
FROM [TABELA DE CLIENTES]
WHERE BAIRRO = 'Jardins'

SELECT SUM([LIMITE DE CREDITO]) AS [LIMITE DE CREDITO]
FROM [TABELA DE CLIENTES]
WHERE BAIRRO = 'Água Santa'

DECLARE @LIMITE_MAXIMO FLOAT, @LIMITE_ATUAL FLOAT
DECLARE @BAIRRO VARCHAR(20)

SET @BAIRRO = 'Água Santa'
SET @LIMITE_MAXIMO = 500000

SELECT @LIMITE_ATUAL = SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] WHERE BAIRRO = @BAIRRO

IF @LIMITE_MAXIMO <= (SELECT SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] WHERE BAIRRO = @BAIRRO)

BEGIN
   PRINT 'Valor estourou. Não é possível abrir novos créditos'
END
ELSE
BEGIN
   PRINT 'Valor não estourou. É possível abrir novos créditos'
END