-- Seleção da base de dados

USE SUCOS_VENDAS

SELECT * FROM dbo.[ITENS NOTAS FISCAIS]

SELECT * FROM dbo.[NOTAS FISCAIS]

SELECT * FROM dbo.[TABELA DE CLIENTES]

SELECT * FROM dbo.[TABELA DE PRODUTOS]

SELECT * FROM dbo.[TABELA DE VENDEDORES]