/* Agrupar dados por [condicao] */

/*
SUM: Soma
MAX: Máximo
MIN: Mínimo
AVG: Média
COUNT: Conta ocorrências (Quantidade)
*/

USE SUCOS_VENDAS

SELECT * FROM [dbo].[TABELA DE CLIENTES]

SELECT ESTADO,  [LIMITE DE CREDITO] AS 'LIMITE DE CREDITO' FROM [dbo].[TABELA DE CLIENTES]

SELECT ESTADO, SUM([LIMITE DE CREDITO]) AS 'SOMA LIMITE DE CREDITO' FROM [TABELA DE CLIENTES] GROUP BY ESTADO

SELECT ESTADO, AVG([LIMITE DE CREDITO]) AS 'MÉDIA LIMITE DE CREDITO' FROM [TABELA DE CLIENTES] GROUP BY ESTADO

SELECT EMBALAGEM, MAX([PREÇO DE LISTA]) AS 'LIMITE DE CREDITO MÁXIMO' FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM

SELECT EMBALAGEM, MIN([PREÇO DE LISTA]) AS 'LIMITE DE CREDITO MÍNIMO'FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM

SELECT [NOME DO PRODUTO], EMBALAGEM  FROM [TABELA DE PRODUTOS] ORDER BY EMBALAGEM

SELECT EMBALAGEM, COUNT(*) AS 'QUANTIDADE' FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM

SELECT BAIRRO, SUM([LIMITE DE CREDITO]) AS 'SOMA' FROM [TABELA DE CLIENTES] 
WHERE [ESTADO]  = 'SP' GROUP BY BAIRRO

SELECT BAIRRO, SUM([LIMITE DE CREDITO]) AS 'SOMA' FROM [TABELA DE CLIENTES] 
WHERE [ESTADO]  = 'SP' GROUP BY BAIRRO ORDER BY BAIRRO DESC

SELECT BAIRRO, ESTADO, SUM([LIMITE DE CREDITO]) AS 'SOMA' FROM [TABELA DE CLIENTES] 
WHERE [ESTADO]  = 'SP' GROUP BY BAIRRO, ESTADO
