/* 14. Consultas condicionais de agragação - HAVING */

USE SUCOS_VENDAS

SELECT * FROM [dbo].[TABELA DE CLIENTES]

SELECT ESTADO, SUM([LIMITE DE CREDITO]) AS 'SOMA' FROM [TABELA DE CLIENTES] GROUP BY ESTADO

SELECT ESTADO, SUM([LIMITE DE CREDITO]) AS 'SOMA' FROM [TABELA DE CLIENTES] GROUP BY ESTADO 
HAVING SUM([LIMITE DE CREDITO]) >= 850000

SELECT EMBALAGEM, SUM([PREÇO DE LISTA]) AS 'SOMA', MAX([PREÇO DE LISTA]) AS 'MAXIMO', MIN([PREÇO DE LISTA]) AS 'MINIMO' 
FROM [TABELA DE PRODUTOS]
GROUP BY EMBALAGEM

SELECT EMBALAGEM, SUM([PREÇO DE LISTA]) AS 'SOMA', MAX([PREÇO DE LISTA]) AS 'MAXIMO', MIN([PREÇO DE LISTA]) AS 'MINIMO' 
FROM [TABELA DE PRODUTOS]
GROUP BY EMBALAGEM
HAVING SUM([PREÇO DE LISTA]) <= 80

SELECT EMBALAGEM, MAX([PREÇO DE LISTA]) AS 'MAXIMO', MIN([PREÇO DE LISTA]) AS 'MINIMO' 
FROM [TABELA DE PRODUTOS]
GROUP BY EMBALAGEM
HAVING SUM([PREÇO DE LISTA]) <= 80

SELECT EMBALAGEM, MAX([PREÇO DE LISTA]) AS 'MAXIMO', MIN([PREÇO DE LISTA]) AS 'MINIMO'
FROM [TABELA DE PRODUTOS]
GROUP BY EMBALAGEM
HAVING SUM([PREÇO DE LISTA]) <= 80 AND MAX([PREÇO DE LISTA]) >= 6
