/* Utilizando o CASE (Semelhante ao IF / ELSE) */

USE SUCOS_VENDAS

SELECT * FROM [TABELA DE PRODUTOS]

SELECT [NOME DO PRODUTO],
CASE WHEN [PREÇO DE LISTA] >= 12 THEN 'PRODUTO CARO'
WHEN [PREÇO DE LISTA] >= 7 AND [PREÇO DE LISTA] < 12 THEN 'PRODUTO EM CONTA'
ELSE 'PRODUTO BARATO' END AS 'CATEGORIA DE PRECO'
FROM [TABELA DE PRODUTOS]

SELECT [NOME DO PRODUTO],
CASE WHEN [PREÇO DE LISTA] >= 12 THEN 'PRODUTO CARO'
WHEN [PREÇO DE LISTA] >= 7 AND [PREÇO DE LISTA] < 12 THEN 'PRODUTO EM CONTA'
ELSE 'PRODUTO BARATO' END AS 'CATEGORIA DE PRECO', 
AVG([PREÇO DE LISTA]) AS 'MEDIA'
FROM [TABELA DE PRODUTOS]
GROUP BY [NOME DO PRODUTO],
CASE WHEN [PREÇO DE LISTA] >= 12 THEN 'PRODUTO CARO'
WHEN [PREÇO DE LISTA] >= 7 AND [PREÇO DE LISTA] < 12 THEN 'PRODUTO EM CONTA'
ELSE 'PRODUTO BARATO' END
-- O CASE WHEN ESTA NO GROUP BY PARA AGRUPAR OS RESULTADOS

SELECT YEAR(DATA) AS 'ANO', COUNT(*) AS 'QUANTIDADE TOTAL NF' FROM [NOTAS FISCAIS] GROUP BY YEAR(DATA)
