/*  DATAS */

USE SUCOS_VENDAS

/* DATA E HORA COMPUTADOR */
SELECT SYSDATETIME() AS [DATA E HORA]
/* DATA E HORA COMPUTADOR + FUSO HORÁRIO */
SELECT SYSDATETIMEOFFSET() AS [DATA E HORA COM FUSO HORARIO]

SELECT SYSUTCDATETIME()

SELECT CURRENT_TIMESTAMP
/* PEGA A DATA ATUAL */
SELECT GETDATE()

SELECT GETUTCDATE()
/* RETORNA O ANO EM STRING */
SELECT DATENAME(YEAR,GETDATE())
/* RETORNA OS MICROSEGUNDOS EM STRING */
SELECT DATENAME(MICROSECOND,GETDATE())
/* RETORNA OS MINUTOS EM STRING  */
SELECT DATENAME(MINUTE,GETDATE())

/* NOME DO MÊS */
SELECT DATENAME(MONTH,GETDATE())
/* NUMERO DO MÊS */
SELECT DATEPART(MONTH,GETDATE())
/* DIA */
SELECT DAY(GETDATE())
/* ANO */
SELECT YEAR(GETDATE())
/* FORMATA OS VALORES EM DATA */
SELECT DATEFROMPARTS(2015,9,1)
/* FORMATA EM DATA E RETORNA O NOME DO MÊS */
SELECT DATENAME(MONTH,DATEFROMPARTS(2015,9,1))
/* FORMATA EM DATA E HORA */
SELECT DATETIME2FROMPARTS(2015,9,1,13,12,11,120,4)
/* DIFERENCA DE DIAS */
SELECT DATEDIFF(MONTH, DATEFROMPARTS(2015,9,1), GETDATE())
/* ADICIONA X MESES NA DATA ATUAL */
SELECT DATEADD(MONTH, 5, GETDATE())

SELECT ISDATE('2018-01-01')

SELECT ISDATE('2018-25-28')

SELECT * FROM [NOTAS FISCAIS]

SELECT [DATA], CONCAT(DATENAME(DAY, [DATA]), ' ', DATENAME(MONTH, [DATA]), ' ', DATENAME(YEAR, [DATA]))
FROM [NOTAS FISCAIS]
