/* 30.Funcoes matemáticas */

USE SUCOS_VENDAS

/* ARREDONDA PARA CIMA */
SELECT CEILING(12.333223) AS NUMERO
/* ARREDONDA PARA BAIXO */
SELECT FLOOR(12.333223) AS NUMERO
/* NÚMERO ALEATÓRIO */
SELECT RAND() AS [VALOR ALEATORIO]
/* VALOR ARREDONDADO PARA 2 CASAS DECIMAIS */
SELECT ROUND(12.33323323, 2)

SELECT * FROM [ITENS NOTAS FISCAIS]

SELECT [QUANTIDADE], [PREÇO], ROUND(([QUANTIDADE] * [PREÇO]),1) AS [TOTAL] FROM [ITENS NOTAS FISCAIS]