/* 32.Conversao de dados */

USE SUCOS_VENDAS
/* DATA ATUAL -  DIA/MES/ANO */
SELECT CONVERT(VARCHAR, GETDATE(), 101) AS [DATA ATUAL]
/* DATA ATUAL -  DIA/MES/ANO HORA:MINUTO:SEGUNDO:MILISSEGUNDO */
SELECT CONVERT(VARCHAR, GETDATE(), 113) AS [DATA ATUAL]
/* DATA ISLAMICA (POSSUI CARACTESRES ESPECIAIS, POR ESSE MOTIVO APARECE ???) */
SELECT CONVERT(VARCHAR, GETDATE(), 130)
/* VALOR 193.57 CONVERTIVO PARA 5 CASAS APOS A VIRGULA: 193.57000*/
SELECT CONVERT(decimal(10,5), 193.57)

SELECT * FROM [TABELA DE PRODUTOS]
/* ERRO: PRECO DE LISTA É UM SMALMONEY, POR ESSE MOTIVO NÃO É POSSIVEL CONCATENAR */
SELECT 'O preço do produto ' + [NOME DO PRODUTO] + ' é ' +  [PREÇO DE LISTA] 
FROM [TABELA DE PRODUTOS]
/* APOS A CONVERS]AO PARA VARCHAR, FOI POSSÍVEL CONCATENAR*/
SELECT 'O preço do produto ' + [NOME DO PRODUTO] + ' é ' +  CONVERT(VARCHAR, [PREÇO DE LISTA]) 
FROM [TABELA DE PRODUTOS]