/* 39.Consultas - Vendas percentuais por tamanho */

/* Modifique o relatório, mas agora para ver o ranking das vendas por tamanho. */

USE SUCOS_VENDAS

SELECT AUX1.TAMANHO, AUX1.ANO, CONVERT(DECIMAL(15,2), AUX1.FATURAMENTO) AS FATURAMENTO, CONVERT(VARCHAR, CONVERT(DECIMAL(15,2), (AUX1.FATURAMENTO/AUX2.TOTAL) * 100)) + ' %' AS PERCENTUAL
FROM(
	SELECT TP.TAMANHO, YEAR(NF.DATA) AS ANO, SUM (INF.QUANTIDADE * INF.PREÇO) AS FATURAMENTO
	FROM [ITENS NOTAS FISCAIS] INF INNER JOIN [TABELA DE PRODUTOS] TP
	ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
	INNER JOIN [NOTAS FISCAIS] NF 
	ON NF.NUMERO = INF.NUMERO
	WHERE YEAR(NF.DATA) = 2016
	GROUP BY TP.TAMANHO, YEAR(NF.DATA)) AUX1
	INNER JOIN (SELECT YEAR(NF.DATA) AS ANO, SUM (INF.QUANTIDADE * INF.PREÇO) AS TOTAL
	FROM [ITENS NOTAS FISCAIS] INF INNER JOIN [TABELA DE PRODUTOS] TP
	ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
	INNER JOIN [NOTAS FISCAIS] NF 
	ON NF.NUMERO = INF.NUMERO
	WHERE YEAR(NF.DATA) = 2016
	GROUP BY YEAR(NF.DATA)
	) AUX2
ON AUX1.ANO = AUX2.ANO
ORDER BY AUX1.FATURAMENTO DESC