/*REMOVE ESPAÇOS A ESQUERDA - LEFT*/
SELECT LTRIM('    OLÁ') AS RESULTADO;
/*REMOVE ESPAÇOS A DIREITA - RIGHT*/
SELECT RTRIM('OLÁ     ') AS RESULTADO;
/*REMOVE ESPACOS A DIRETA E ESQUERDA*/
SELECT TRIM('    OLÁ    ') AS RESULTADO;
/*CONCATENA AS STRING*/
SELECT CONCAT('OLÁ', ' ', 'TUDO BEM','?') AS RESULTADO;
/*DEIXA AS LETRAS EM MAIÚSCULAS*/
SELECT UPPER('olá, tudo bem?') AS RESULTADO;
/*DEIXA AS LETRAS EM MINÚSCULAS*/
SELECT LOWER('OLÁ, TUDO BEM?') AS RESULTADO;
/*EXIBIR A PARTIR DA POSIÇÃO 6*/
SELECT SUBSTRING('OLÁ, TUDO BEM?', 6) AS RESULTADO;
/*EXIBIR A PARTIR DA POSIÇÃO 6 OS 4 CARACTERES QUE ESTÃO NA SEQUENCIA*/
SELECT SUBSTRING('OLÁ, TUDO BEM?', 6, 4) AS RESULTADO;

SELECT CONCAT(NOME, ' (', CPF, ') ') AS RESULTADO FROM TABELA_DE_CLIENTES;









