/*CALCULO SIMPLES (ADIÇÃO, SUBTRAÇÃO, DIVISÃO E MULTIPLICAÇÃO)*/
SELECT (23+((25-2)/2)*45) AS RESULTADO;
/*ARREDONDA PARA CIMA*/
SELECT CEILING(12.33333232323) AS RESULTADO;
/*ARREDONDA O NÚMERO, DEFAULT 0 CASAS DECIMAIS*/
SELECT ROUND(12.7777232323) AS RESULTADO;
/*ARREDONDA O NÚMERO PARA 2 CASAS DECIMAIS*/
SELECT ROUND(12.7777232323, 2) AS RESULTADO;
/*ARREDONDA PARA BAIXO*/
SELECT FLOOR(12.7777232323) AS RESULTADO;
/*NÚMERO ALEATÓRIO*/
SELECT RAND() AS RESULTADO; 

SELECT NUMERO, QUANTIDADE, PRECO, QUANTIDADE * PRECO AS FATURAMENTO
 FROM ITENS_NOTAS_FISCAIS;
 
 SELECT NUMERO, QUANTIDADE, PRECO, ROUND(QUANTIDADE * PRECO, 2) AS FATURAMENTO
 FROM ITENS_NOTAS_FISCAIS;