/*DATA ATUAL*/
SELECT CURRENT_TIMESTAMP() AS RESULTADO;

/*CONCATENAÇÃO DE STRING COM VARIÁVEL*/
SELECT CONCAT('O dia de hoje é : ', CURRENT_TIMESTAMP()) AS RESULTADO;

/*FORMTAÇÃO DE DATA - NOME DA SEMANA, DIA, MES, ANO E NÚMERO DA SEMAN*/
SELECT CONCAT('O dia de hoje é : ', 
DATE_FORMAT(CURRENT_TIMESTAMP(),'%W, %d/%m/%Y - %U') ) AS RESULTADO;

/*CONVERTER O NÚMERO EM STRING*/
SELECT SUBSTRING(CONVERT(23.3, CHAR),1,1) AS RESULTADO;